### PR TITLE
Support OCaml 4.12

### PR DESCRIPTION
**Pull request by lthms**
:tada:

### CODE REVIEW

**Comment by lthms** [comment]
And, it’s green, finally.

**Comment by clarus** [comment]
image

**Comment by lthms** [comment]
There are still several blocking points for a working `4.12` branch, but you can have a look at https://gitlab.com/tezos/tezos/-/merge_requests/2671 if you want one that _compiles_ (but fail at linking).

**Comment by lthms** [comment]
So many conflicts :scream:  Do you want me to fix them?

**Comment by clarus** [comment]
Oula. So I think there are more conflicts than actually needed. I guess this is because I upgraded Merlin to `3.4.2` while you do the upgrade to another version. So for the `merlin` folder you can just overwrite everything I have done. I have imported the changes you have made on `src/coqOfOCaml.ml` so on this file the changes should already be done.

**Comment by clarus** [comment]
(I have done the upgrade to 3.4.2 in order to be compatible with OCaml 4.10)

**Comment by clarus** [comment]
I am going to look at it this afternoon. Hoping to run be able to run it on a branch with 4.10 and 4.12 to compare the results. If not, it is still better to do the upgrade than nothing.

**Pull request merged**
